ci(github): allow back Docker access to OpenSSF since required (#199)
The error was:

> Error: An error occurred trying to start process '/usr/bin/docker' with working directory '/home/runner/work/docker-papermc-server/docker-papermc-server'. No such file or directory